### ISSUE TITLE
list.remove(x): x not in list

### ISSUE THREAD

**Issue by gtejeda** [NathanEpstein/Dora#10]

**Comment by gtejeda** [comment]
Greetings
this is a really great idea to simply data cleaning, thanks.
I'm having an issue imputing missing values.

I've only opened my csv as per the demos:
dora = Dora(output = 'A', data = df)
dora.data

I checked if there were columns with missing values:
nan_cols = [i for i in df.columns if df[i].isnull().any()]

then I did this:
dora.impute_missing_values()

and I get this error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-3ba44a3a1b32> in <module>()
----> 1 dora.impute_missing_values()

c:\IntelPython3\lib\site-packages\Dora\main.py in impute_missing_values(self)
     34 
     35   def impute_missing_values(self):
---> 36     column_names = self.input_columns()
     37     imp = preprocessing.Imputer()
     38     imp.fit(self.data[column_names])

c:\IntelPython3\lib\site-packages\Dora\main.py in input_columns(self)
     82   def input_columns(self):
     83     column_names = list(self.data.columns)
---> 84     column_names.remove(self.output)
     85     return column_names
     86 

**ValueError: list.remove(x): x not in list**`



Any help will be greatly appreciated.

**Comment by ntsvetanov** [comment]
The output variable is the target variable for your dataset. You should pass desired target variable column name from your dataset istead of output = 'A'

**Comment by NathanEpstein** [comment]
Thanks @ntsvetanov for clarifying!
