### ISSUE TITLE
Dora.explore() issue

### ISSUE THREAD

**Issue by iwidodo** [NathanEpstein/Dora#12]
When I try running the Dora.explore() method, I get an Attribute error:
AttributeError: 'Dora' object has no attribute 'input_data'

I believe this might be because the explore() method in main calls Dora.input_data().columns instead of Dora.input_columns(). Am I missing something/is this fixable? Thanks.

**Comment by NathanEpstein** [comment]
Updated and deployed a new version of the library code to PyPI. Thanks for flagging!
