### ISSUE TITLE
Dora version error

### ISSUE THREAD

**Issue by MarcosTavarez** [NathanEpstein/Dora#18]
I believe there is a version error. Upon looking at the setup.py file I noticed that version 0.0.3 was removed and 0.0.4 was added. I tried to install using 0.0.4 but said that the version does not exist.

This all derived from me trying to mitigate the issue of sklearn being deprecated.

**Comment by vtjeng** [comment]
This is a result of the package not being released at pypi.org:

https://pypi.org/project/Dora/#history

@NathanEpstein will have to do it (probably following the instructions at https://pythonpackaging.info/07-Package-Release.html#Uploading-your-package-to-the-Python-Package-Index-(PyPI)).

**Comment by Aldair502** [comment]
> I believe there is a version error. Upon looking at the setup.py file I noticed that version 0.0.3 was removed and 0.0.4 was added. I tried to install using 0.0.4 but said that the version does not exist.
> 
> This all derived from me trying to mitigate the issue of sklearn being deprecated.

use this repo has the dependency then. it should be a permanent fix

**Comment by NathanEpstein** [comment]
As @Aldair502 says, this repo should be the dependency. Thanks for raising!
