### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by vjayd** [NathanEpstein/Dora#8]
Getting this error when i run
dataframe = pd.read_csv("test.csv");
dora = Dora(output = 'A', data = dataframe)
dora.data
dora.impute_missing_values()

**Comment by NathanEpstein** [comment]
Thanks for reaching out. Unfortunately, not enough in this issue to address. Happy to revisit if you could provide a bit more detail (i.e. some details about the values in your dataframe and most importantly, a stack trace for the actual error). Thanks!
