### ISSUE TITLE
features = self.input_data().columns

### ISSUE THREAD

**Issue by mathematixy** [NathanEpstein/Dora#9]
`features = self.input_data().columns`

should be replaced by:
`features = self.input_columns()`

```
  def explore(self):
    features = self.input_columns()
    row_count = math.floor(math.sqrt(len(features)))
    col_count = math.ceil(len(features) / row_count)
    figure = plt.figure(1)
```

**Comment by NathanEpstein** [comment]
Seems like these should be equivalent? If not, you're welcome to make a PR highlighting the proposed behavior change.
